#!/usr/bin/env bash
set -eu

PROVIDER_DIR="${PKCS11_PROVIDER_DIR:-/providers}"
SCD_HOMEDIR="${SCD_HOMEDIR:-/var/lib/gnupg-pkcs11-scd}"
SCD_SOCKET_DIR="${SCD_SOCKET_DIR:-/var/run/gnupg-pkcs11-scd}"
CONF="${SCD_HOMEDIR}/gnupg-pkcs11-scd.conf"

# --- Step 0: ensure runtime paths exist and are writable ---
if ! mkdir -p "$SCD_HOMEDIR" 2>/dev/null; then
  echo "Failed to create or access SCD_HOMEDIR: $SCD_HOMEDIR" >&2
  echo "Ensure the path is writable by UID $(id -u)." >&2
  exit 1
fi

if ! mkdir -p "$SCD_SOCKET_DIR" 2>/dev/null; then
  echo "Failed to create or access SCD_SOCKET_DIR: $SCD_SOCKET_DIR" >&2
  echo "Ensure the path is writable by UID $(id -u)." >&2
  exit 1
fi

# --- Step 1: determine provider list ---
if [ "${PKCS11_PROVIDERS+set}" = set ]; then
  IFS=',' read -r -a raw <<<"$PKCS11_PROVIDERS"
else
  raw=()
  if [ -d "$PROVIDER_DIR" ]; then
    for d in "$PROVIDER_DIR"/*; do
      [ -d "$d" ] || continue
      raw+=("$(basename "$d")")
    done
  fi
fi

providers=()
for n in "${raw[@]}"; do
  n="${n// /}"
  [ -n "$n" ] && providers+=("$n")
done

if [ "${#providers[@]}" -eq 0 ]; then
  echo "PKCS11_PROVIDERS is empty and no provider directories found under $PROVIDER_DIR." >&2
  echo "Mount at least one provider image at $PROVIDER_DIR/<name>/, or set PKCS11_PROVIDERS explicitly." >&2
  exit 1
fi

explicit_set() { [ "${PKCS11_PROVIDERS+set}" = set ]; }

# --- Step 2: resolve library path per provider ---
lines=()
resolved_names=()
for name in "${providers[@]}"; do
  upper=$(printf '%s' "$name" | tr '[:lower:]' '[:upper:]' | tr -c '[:alnum:]' '_')
  override_var="PKCS11_PROVIDER_${upper}_LIBRARY"
  override="${!override_var:-}"

  if [ -n "$override" ] && [ -f "$override" ]; then
    lib="$override"
  else
    shopt -s nullglob
    matches=( "$PROVIDER_DIR/$name/lib${name}"*.so )
    shopt -u nullglob
    case "${#matches[@]}" in
      1) lib="${matches[0]}" ;;
      0)
        if explicit_set; then
          echo "No lib${name}*.so found at $PROVIDER_DIR/$name/ (and \$$override_var not set or invalid)." >&2
          exit 1
        else
          continue
        fi
        ;;
      *)
        echo "Multiple .so files found for provider '$name' under $PROVIDER_DIR/$name/:" >&2
        printf '  %s\n' "${matches[@]}" >&2
        echo "Set $override_var to disambiguate." >&2
        exit 1
        ;;
    esac
  fi

  lines+=( "" "# provider: $name" "provider-${name}-library ${lib}" )
  resolved_names+=("$name")
done

if [ "${#resolved_names[@]}" -eq 0 ]; then
  echo "No providers resolved after library lookup." >&2
  exit 1
fi

# --- Step 3: write config ---
{
  echo "# Generated by entrypoint.sh — do not edit by hand."
  printf 'providers %s\n' "$(IFS=,; echo "${resolved_names[*]}")"
  printf '%s\n' "${lines[@]}"
} > "$CONF"

# --- Step 4: exec daemon ---
export GNUPG_PKCS11_SOCKETDIR="$SCD_SOCKET_DIR"
exec gnupg-pkcs11-scd --multi-server --homedir "$SCD_HOMEDIR"
